CXXFLAGS=-fPIC -Wall -W -O3 -I. -I/Users/vancleve/science/code/fwdpp `python-config --includes` -std=c++11 
LDFLAGS=`python-config --ldflags` -lboost_python -lboost_system -lgsl -lgslcblas 

all: social_evol_inf_alleles.o
	$(CXX) -shared -o social_evol_inf_alleles.so social_evol_inf_alleles.o $(LDFLAGS)

clean:
	rm -f social_evol_inf_alleles.o social_evol_inf_alleles.so
