CXXFLAGS = -fPIC -Wall -Wextra -I. -I/Users/vancleve/science/code/fwdpp `python-config --includes` -std=c++11 
LDFLAGS = `python-config --ldflags` -lboost_python -lboost_system -lgsl -lgslcblas 

debug: social_evol_inf_alleles
debug: CXXFLAGS += -g -O0

nodebug: social_evol_inf_alleles
nodebug: CXXFLAGS += -O3 -DNDEBUG

social_evol_inf_alleles: social_evol_inf_alleles.o
	$(CXX) -shared -o social_evol_inf_alleles.so social_evol_inf_alleles.o $(LDFLAGS)

clean:
	rm -f social_evol_inf_alleles.o social_evol_inf_alleles.so
